import type { MinecraftData, GeneratorResult, Config } from "../types.js";

export type Generator = (data: MinecraftData, config: Config) => GeneratorResult;

export function fileHeader(lang: "rust" | "ts" | "wgsl", mcVersion: string, protocolVersion: number): string {
  const comment = lang === "rust" ? "//" : "//";
  return `${comment} Auto-generated by mc-extract — DO NOT EDIT\n${comment} Minecraft ${mcVersion} (protocol ${protocolVersion})`;
}

export function toScreamingSnake(name: string): string {
  return name
    .replace(/^packet_/, "")
    .replace(/([a-z])([A-Z])/g, "$1_$2")
    .replace(/[^a-zA-Z0-9]/g, "_")
    .toUpperCase();
}

export { generateRustPacketIds } from "./rust-packet-ids.js";
export { generateRustEntityIds } from "./rust-entity-ids.js";
export { generateTsItemBlockMap } from "./ts-item-block-map.js";
export { generateTsBlockIds } from "./ts-block-ids.js";
export { generateWgslBlockConstants } from "./wgsl-block-constants.js";
export { generateTsProtocolMeta } from "./ts-protocol-meta.js";
export { generateRustBlockRegistry } from "./rust-block-registry.js";
export { generateTsPacketNames } from "./ts-packet-names.js";
export { generateTsPacketSchemas } from "./ts-packet-schemas.js";
