import { describe, test, expect } from "bun:test";
import { loadMinecraftData } from "./data-loader";
import {
  generateRustPacketIds,
  generateRustEntityIds,
  generateTsItemBlockMap,
  generateTsBlockIds,
  generateWgslBlockConstants,
  generateTsProtocolMeta,
  generateTsPacketNames,
} from "./generators/index";
import config from "../mc-extract.config";
import type { Config } from "./types";

const data = loadMinecraftData(config.version);
const cfg = config as Config;

describe("data-loader", () => {
  test("loads minecraft-data for configured version", () => {
    expect(data.version.version).toBe(774);
    expect(data.version.minecraftVersion).toBe("1.21.11");
  });

  test("has expected data counts", () => {
    expect(data.blocksArray.length).toBeGreaterThanOrEqual(1100);
    expect(data.entitiesArray.length).toBeGreaterThanOrEqual(150);
    expect(data.itemsArray.length).toBeGreaterThanOrEqual(1400);
  });
});

describe("rust-packet-ids", () => {
  const result = generateRustPacketIds(data, cfg);

  test("generates valid Rust module structure", () => {
    expect(result.content).toContain("pub mod serverbound {");
    expect(result.content).toContain("pub mod clientbound {");
    expect(result.content).toContain("pub mod play {");
  });

  test("contains expected serverbound play packet IDs", () => {
    expect(result.content).toContain("pub const TELEPORT_CONFIRM: i32 = 0x00;");
    expect(result.content).toContain("pub const POSITION: i32 = 0x1D;");
    expect(result.content).toContain("pub const POSITION_LOOK: i32 = 0x1E;");
    expect(result.content).toContain("pub const KEEP_ALIVE: i32 = 0x1B;");
    expect(result.content).toContain("pub const CHAT_MESSAGE: i32 = 0x08;");
  });

  test("contains expected clientbound play packet IDs", () => {
    expect(result.content).toContain("pub const SPAWN_ENTITY: i32 = 0x01;");
    expect(result.content).toContain("pub const MAP_CHUNK: i32 = 0x2C;");
    expect(result.content).toContain("pub const LOGIN: i32 = 0x30;");
    expect(result.content).toContain("pub const SYSTEM_CHAT: i32 = 0x77;");
    expect(result.content).toContain("pub const ENTITY_TELEPORT: i32 = 0x7B;");
    expect(result.content).toContain("pub const RESPAWN: i32 = 0x50;");
  });

  test("has auto-generated header", () => {
    expect(result.content).toStartWith("// Auto-generated by mc-extract");
    expect(result.content).toContain("protocol 774");
  });
});

describe("rust-entity-ids", () => {
  const result = generateRustEntityIds(data, cfg);

  test("contains player entity ID", () => {
    expect(result.content).toContain("pub const PLAYER: i32 = 155;");
  });

  test("contains common entity types", () => {
    expect(result.content).toContain("pub const ZOMBIE: i32 =");
    expect(result.content).toContain("pub const CREEPER: i32 =");
    expect(result.content).toContain("pub const SKELETON: i32 =");
  });

  test("has all entities", () => {
    const constCount = (result.content.match(/pub const /g) || []).length;
    expect(constCount).toBe(data.entitiesArray.length);
  });
});

describe("wgsl-block-constants", () => {
  const result = generateWgslBlockConstants(data, cfg);

  test("generates WGSL constant declarations", () => {
    expect(result.content).toContain("const AIR: u32 = 0u;");
    expect(result.content).toContain("const STONE: u32 = 1u;");
    expect(result.content).toContain("const GRASS_BLOCK: u32 =");
  });

  test("exports as TypeScript string", () => {
    expect(result.content).toContain("export const BLOCK_CONSTANTS_WGSL");
  });

  test("has all blocks", () => {
    const constCount = (result.content.match(/^const \w+: u32/gm) || []).length;
    expect(constCount).toBe(data.blocksArray.length);
  });
});

describe("ts-block-ids", () => {
  const result = generateTsBlockIds(data, cfg);

  test("generates BlockState object", () => {
    expect(result.content).toContain("export const BlockState = {");
    expect(result.content).toContain("AIR: 0");
    expect(result.content).toContain("STONE: 1");
  });

  test("has all blocks", () => {
    const entryCount = (result.content.match(/^\s+\w+: \d+/gm) || []).length;
    expect(entryCount).toBe(data.blocksArray.length);
  });
});

describe("ts-item-block-map", () => {
  const result = generateTsItemBlockMap(data, cfg);

  test("generates item-to-block mapping", () => {
    expect(result.content).toContain("export const ITEM_TO_BLOCK: Record<number, number>");
  });

  test("has substantial number of mappings", () => {
    // Parse the JSON to count entries
    const match = result.content.match(/= ({[^}]+})/);
    expect(match).not.toBeNull();
    const map = JSON.parse(match![1]);
    expect(Object.keys(map).length).toBeGreaterThanOrEqual(800);
  });

  test("maps stone item to stone block state", () => {
    const match = result.content.match(/= ({[^}]+})/);
    const map = JSON.parse(match![1]);
    // Stone item (id=1) should map to stone defaultState (1)
    expect(map["1"]).toBe(1);
  });
});

describe("ts-packet-names", () => {
  const result = generateTsPacketNames(data, cfg);

  test("contains serverbound play packet names", () => {
    expect(result.content).toContain('"in:Play:0x00": "Teleport Confirm"');
    expect(result.content).toContain('"in:Play:0x1d": "Position"');
    expect(result.content).toContain('"in:Play:0x08": "Chat Message"');
  });

  test("contains clientbound play packet names", () => {
    expect(result.content).toContain('"out:Play:0x01": "Spawn Entity"');
    expect(result.content).toContain('"out:Play:0x2c": "Map Chunk"');
    expect(result.content).toContain('"out:Play:0x77": "System Chat"');
  });

  test("exports getPacketName function", () => {
    expect(result.content).toContain("export function getPacketName");
  });

  test("covers all states and directions", () => {
    expect(result.content).toContain('"in:Handshaking:');
    expect(result.content).toContain('"in:Status:');
    expect(result.content).toContain('"in:Login:');
    expect(result.content).toContain('"in:Configuration:');
    expect(result.content).toContain('"out:Status:');
    expect(result.content).toContain('"out:Login:');
    expect(result.content).toContain('"out:Configuration:');
    expect(result.content).toContain('"out:Play:');
  });
});

describe("ts-protocol-meta", () => {
  const result = generateTsProtocolMeta(data, cfg);

  test("exports protocol version", () => {
    expect(result.content).toContain("export const PROTOCOL_VERSION = 774;");
  });

  test("exports minecraft version", () => {
    expect(result.content).toContain('export const MINECRAFT_VERSION = "1.21.11";');
  });
});
